SBFPTInegasiquanta/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio_page.urls')),
    path('messages/', include('msg.urls'))
]

msg/urls.py
from . import views
from django.urls import path
app_name = 'msg'

urlpatterns = [
    path('', views.message_list, name='message_list'),
    path('message_create/', views.message_create, name="message_create"),
    path('comment_create/<int:message_id>/', views.comment_create, name="comment_create"),           
]

portfolio_page/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='portfolio_page'
urlpatterns = [
    path('', views.index, name='homepage')
]

msg/models.py
from django.db import models

class Message(models.Model):
    submiter = models.CharField(max_length=50)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return "{} - {}".format(self.submiter, self.snipped_message())
    
    def snipped_message(self):
        if len(self.message) > 20 :
            return self.message[:20] + " ..."
        return self.message

class Comment(models.Model):
    submiter = models.CharField(max_length=50)
    comment = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, blank=True, null=True, related_name="comments")

    def __str__(self):
        return "{} - {}".format(self.submiter, self.comment)

msg/forms.py
from . import models
from django import forms

class CreateMessageForm(forms.Form):
    submiter = forms.CharField(widget=forms.TextInput(attrs={
            "class" : "fields",
            "required" : True,
            "placeholder":"Your Name"
             }), max_length=50)
    
    message = forms.CharField(widget=forms.Textarea(attrs={
            "class" : "fields",
            "required" : True,
            "placeholder":"Your Message Here Asshole"
             }), max_length=50)
    
    class Meta:
           model = models.Message

class CommentForm(forms.Form):
        submiter = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "fields",
                "required" : True,
                "placeholder":"Your Name"
                }), max_length=50)
    
        comment = forms.CharField(widget=forms.Textarea(attrs={
                "class" : "fields",
                "required" : True,
                "placeholder":"Your Message Here Asshole"
                }), max_length=50)
    
        class Meta:
                model = models.Message

msg/views.py
from django.shortcuts import render,redirect
from .import forms
from .models import Message,Comment

def message_list(request):
    messages = Message.objects.all()
    message_form = forms.CreateMessageForm()
    comment_form = forms.CommentForm()
    response = {
         'msgs' : messages,
         'form' : message_form,
         'comment_form' : comment_form
    }
    return render(request, 'msg/message_list.html', response)

def message_create(request):
    message_form = forms.CreateMessageForm(request.POST)
    if request.method == "POST" and message_form.is_valid():
        Message.objects.create(
            submiter = message_form.cleaned_data['submiter'],
            message = message_form.cleaned_data['message']
        )
    return redirect('msg:message_list')

def comment_create(request, message_id):
    comment_form = forms.CommentForm(request.POST)
    if request.method == "POST" and comment_form.is_valid():
        Comment.objects.create(
            submiter = comment_form.cleaned_data['submiter'],
            comment = comment_form.cleaned_data['comment'],
            message = Message.objects.get(id=message_id)
        )
    return redirect('msg:message_list')

portfolio_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "portfolio_page/SBFTEST.html")

msg/templates/msg/message_list.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"  href="{% static 'msg/style1.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>
<body>
    {% for message in msgs %}
    <div class="msgbox">
        <h3>{{ message.submiter }}</h6>
        <p>{{ message.message }}</p>
        <p>{{ message.created_at }}</p>
    </div>
    <form  method="POST" action="{% url 'msg:comment_create' message_id=message.id %}">
        {% csrf_token %}
        <div>
            {% for field in comment_form.visible_fields %}
                {{ field }}
            {% endfor %}
        <div>
        <button type="submit">Add!</button>
    </form>
            {% for comment in message.comments.all %}
                <div>
                {{ comment.comment }} by {{ comment.submiter }}
                </div>
            {% endfor %}
        {% endfor %}
    <form action="{% url 'msg:message_create' %}" method="POST">
        {% csrf_token %}
        <div class="forme">
            {% for field in form.visible_fields %}
                <div style="width:80%;">{{ field }}</div>
            {% endfor %}
        </div>
        <button type="submit">Add!</button>
    </form>
</body>
</html>

portfolio_page/templates/portfolio_page/SBFTEST.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
    <title>Leonardo</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet"  href="{% static 'portfolio_page/style.css' %}">
    </head>
    <body>
        <div class="topnav">
            <a href="/messages">Messages</a>
            <a href="#sosmed">Social</a>
            <a href="#skill">Skill</a>
            <a href="#hobby">Hobby</a>
            <a href="#education">Education</a>
            <a href="#AboutMe">ME</a>
        </div>
        <div id="AboutMe">
            <center>
                <div class="picture"></div>
                <div>
                    <h1>LEONARDO</h1>
                    <h3 class="birth">Born 7th August 2000</h3>
                    <h3 class="major">Information System-18</h3> 
                    <h3 class="major">Faculty of Computer Science</h3>  
                    <h3 class="major">University of Indonesia</h3>  
                </div>
            </center>
        </div>
        <div class="test">
            <div class="topbox" id="education">
                <center>
                    <h1>Education</h1>
                    <div class="block" id="sd">
                        <h3 class="left">Fajar Sion Elementary School</h3>
                        <h3 class="right">(2006-2012)</h3>
                    </div>
                    <div class="block" id="smp">
                        <h3 class="left">Kalam Kudus 1 Junior Highschool</h3>
                        <h3 class="right">(2012-2015)</h3>
                    </div>
                    <div class="block" id="sma">
                        <h3 class="left">Methodist Highschool</h3>
                        <h3 class="right">(2015-2018)</h3>
                    </div>
                    <div class="block" id="ui">
                        <h3 class="left">University of Indonesia</h3>
                        <h3 class="right">(2018-Now)</h3>
                    </div>
                </center>
            </div>
            <div class="topbox" id="hobby">
                <center>
                    <h1>Hobby</h1>
                    <h3>Table Tennis</h3>
                    <h3>Sports</h3>
                    <h3>Watch Movies</h3>  
                </center>
            </div>
            <div class="topbox" id="skill">
                <center>
                    <h1>Skills</h1>
                    <h3>Programing</h3>
                    <h3>Table Tennis</h3>
                </center>
            </div>  
        </div>       
        <div class="sosmedbox" id="sosmed">
            <h1>Follow Me</h1>
            <div class="ssbox" id="line">
                <div class="mid">
                    <a href="https://line.me/en-US/" target="_blank">
                        <h2><b>Line</b></h2>
                        <h3>ID : leonardo2000</h3>
                    </a>
                </div>
            </div>
            <div class="ssbox" id="instagram">
                <div class="mid">
                    <a href="https://www.instagram.com/leonardo7820/" target="_blank">
                        <h2><b>Instagram</b></h2>
                        <h3>@leonardo7820</h3>
                    </a>                    
                </div>
            </div>
            <div class="ssbox" id="gmail">
                <div class="mid">
                    <a href="https://www.gmail.com/" target="_blank">
                        <h2><b>Gmail</b></h2>
                        <h4>leonardoeinstein2000@gmail.com</h4>
                    </a>
                </div>
            </div>    
        </div>  
    </body>
</html>